// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions, Firebase;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLW9fUgaTFtni8mIpRkOqy0xskcY5pcMM',
    appId: '1:1073061714671:web:0e00d80c68445dd754d91a',
    messagingSenderId: '1073061714671',
    projectId: 'hiit-timer-41b79',
    authDomain: 'hiit-timer-41b79.firebaseapp.com',
    databaseURL: 'https://hiit-timer-41b79.firebaseio.com',
    storageBucket: 'hiit-timer-41b79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEaTaf5LpGHK5gfem1eLBlsnpwlwvyd5I',
    appId: '1:1073061714671:android:cdeab797057bf74254d91a',
    messagingSenderId: '1073061714671',
    projectId: 'hiit-timer-41b79',
    databaseURL: 'https://hiit-timer-41b79.firebaseio.com',
    storageBucket: 'hiit-timer-41b79.appspot.com',
  );
}
